#!/usr/bin/env sh
# vim:tw=80:ts=4:sw=4:ai:et:ff=unix:fenc=utf-8:et:fixeol:eol:fdm=marker:fdl=0:fen:ft=sh
#
# A script to help manage the project during development.

usage() {
    cat <<EOF Usage: ./dev [command=dev]

Options:

    dev (default)
        Runs the project in development mode.

    release
        Produces a release.

    help
        Shows this message.

EOF

}

dev() {
    echo 'TODO: add commands here to run in development mode'
}

release() {
    echo 'TODO: add commands here to prepare a release'
}

main() {
    local cmd="${1:-dev}"
    if [ $# -gt 0 ]; then
        shift
    fi

    case "$cmd" in
        dev) dev "$@" ;;
        release) release "$@" ;;
        help) usage; return 1 ;;
        *)
            usage
            echo "ERROR: Invalid command: '$cmd'"
            return 1
            ;;
    esac
    return 0
}

main "$@"
