packages:
  - "packages/*"

catalog:
  "@tailwindcss/typography": "0.5.14"
  "@trivago/prettier-plugin-sort-imports": "^4.3.0"
  "@types/node": "^20.14.5"
  "chrome-types": "^0.1.297"
  "daisyui": "^4.12.10"
  "esbuild": "0.23.0"
  "eslint": "^9.8.0"
  "eslint-config-google": "^0.14.0"
  "eslint-config-prettier": "^9.1.0"
  "marked": "14.0.0"
  "npm-run-all": "^4.1.5"
  "npm-run-all2": "^6.2.0"
  "prettier": "^3.3.3"
  "prettier-plugin-tailwindcss": "^0.6.5"
  "tailwindcss": "^3.4.7"
  "typescript": "^5.5.3"
  "vite": "^5.3.5"
