packages:
  - "packages/*"

catalog:
  ##
  ##
  ## Packages I use in most projects.
  ##

  "@eslint/js": "9.10.0"
  "@tailwindcss/typography": "0.5.14"
  "@trivago/prettier-plugin-sort-imports": "^4.3.0"
  "@types/node": "^20.14.5"
  "autoprefixer": "^10.4.20"
  "chrome-types": "^0.1.297"
  "daisyui": "^4.12.10"
  "esbuild": "0.23.0"
  "eslint": "^9.8.0"
  "eslint-config-google": "^0.14.0"
  "eslint-config-prettier": "^9.1.0"
  "mermaid": "11.2.1"
  "npm-run-all2": "^6.2.0"
  "postcss": "^8.4.47"
  "prettier": "^3.3.3"
  "prettier-plugin-tailwindcss": "^0.6.5"
  "tailwindcss": "^3.4.11"
  "typescript": "^5.5.3"
  "vite": "^5.3.5"

  ##
  ##
  ## Packages I use in some projects.
  ##

  "@google/generative-ai": "0.16.0"
  "@rollup/plugin-babel": "^6.0.4"
  "@types/shelljs": "0.8.15"
  "babel-plugin-htm": "^3.0.0"
  "htm": "^3.1.1"
  "marked": "14.0.0"
  "preact": "^10.23.1"
  "shelljs": "0.8.5"
  "vue": "^3.4.36"
  "zx": "8.1.4"

  ##
  ##
  ## Packages that I replaced with others but still use in some projects.
  ##

  "npm-run-all": "^4.1.5" # Replaced by `npm-run-all2`
