packages:
  ## The default packages location.
  - "packages/*"

  ## Add other packages here.
  ## - "example"
  ## - "other/example"

catalog:
  ##
  ##
  ## Packages I use in most projects.
  ##

  "@eslint/js": "9.10.0"
  "@tailwindcss/typography": "0.5.14"
  "@trivago/prettier-plugin-sort-imports": "4.3.0"
  "@types/node": "22.7.4"
  "autoprefixer": "10.4.20"
  "chrome-types": "0.1.297"
  "daisyui": "4.12.10"
  "esbuild": "0.23.0"
  "eslint": "9.8.0"
  "eslint-config-google": "0.14.0"
  "eslint-config-prettier": "9.1.0"
  "mermaid": "11.2.1"
  "npm-run-all2": "6.2.0"
  "postcss": "8.4.47"
  "postcss-nested": "6.2.0"
  "prettier": "3.3.3"
  "prettier-plugin-tailwindcss": "0.6.5"
  "tailwindcss": "3.4.11"
  "typescript": "5.6.2"
  "vite": "5.4.10"

  ##
  ##
  ## Packages I use in some projects.
  ##

  "@google/generative-ai": "0.16.0"
  "@msgpack/msgpack": "3.0.0-beta2"
  "@rollup/plugin-babel": "6.0.4"
  "@types/lodash": "4.17.9"
  "@types/qunit": "2.19.10"
  "@sveltejs/vite-plugin-svelte": "4.0.0"
  "@tsconfig/svelte": "5.0.4"
  "@types/shelljs": "0.8.15"
  "@vitejs/plugin-react": "4.3.1"
  "babel-plugin-htm": "3.0.0"
  "chokidar": "4.0.1"
  "gulp": "5.0.0"
  "htm": "3.1.1"
  "lit": "3.2.1"
  "lodash": "4.17.21"
  "marked": "14.0.0"
  "preact": "10.23.1"
  "qunit": "2.22.0"
  "react": "18.3.1"
  "react-dom": "18.3.1"
  "shelljs": "0.8.5"
  "svelte": "5.1.3"
  "svelte-check": "4.0.5"
  "tslib": "2.8.0"
  "vue": "3.4.36"
  "ws": "8.18.0"
  "zx": "8.1.4"

  ##
  ##
  ## Packages that I replaced with others but still use in some projects.
  ##

  # Replaced by `npm-run-all2`.
  "npm-run-all": "4.1.5"
