#!/usr/bin/env sh

# TODO: uncomment the following when we have tests.
# npm test

prettier $(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g') --write --ignore-unknown
git update-index --again
